"""月次リバランスと長期保有型の購入価格取得方法の違いを確認"""

print("=" * 80)
print("月次リバランスと長期保有型の購入価格取得方法の違い")
print("=" * 80)
print()

print("【月次リバランス（calculate_timeseries_returns）】")
print("-" * 80)
print("1. _get_next_trading_day(conn, rebalance_date) で翌営業日を取得")
print("2. _get_prices_bulk(conn, codes, [purchase_date], use_open=True) で購入価格を一括取得")
print("3. purchase_priceがNULLの銘柄は portfolio_valid から除外")
print("4. 有効な銘柄だけでリターンを計算（欠損銘柄は自動的に除外される）")
print("5. すべての銘柄で購入価格が取得できない場合でも、エラーにはならない")
print("   → portfolio_valid.empty の場合は stock_returns = [] となり、")
print("      monthly_returns.append(0.0) として0%のリターンを返す")
print()

print("【長期保有型（calculate_portfolio_performance）】")
print("-" * 80)
print("1. _get_next_trading_day(conn, rebalance_date) で翌営業日を取得")
print("2. 各銘柄ごとに個別に購入価格（open）を取得")
print("3. 購入価格が取得できない銘柄は missing_buy_prices に追加")
print("4. すべての銘柄で購入価格が取得できない場合、警告を出力")
print("5. coverage=0.0000 となり、そのポートフォリオは集計から除外される")
print("   → total_return_pct が None になり、calculate_longterm_performance で除外")
print()

print("=" * 80)
print("問題が表面化しなかった理由")
print("=" * 80)
print()

print("【月次リバランス】")
print("✅ 欠損銘柄を自動的に除外して計算するため、問題が表面化しなかった")
print("   - 2020-10-01のデータがNULLでも、その銘柄が除外されるだけで計算が続行")
print("   - ただし、修正前の_get_next_trading_dayは2020-10-01を返していた可能性がある")
print("   - その場合、_get_prices_bulkで2020-10-01のopenがNULLになり、")
print("     その銘柄が除外されたが、エラーにはならなかった")
print()

print("【長期保有型】")
print("⚠️  明示的に購入価格を取得しようとするため、問題が表面化した")
print("   - 修正前の_get_next_trading_dayは2020-10-01を返していた")
print("   - 2020-10-01のopenがすべてNULLのため、すべての銘柄で購入価格が取得できなかった")
print("   - 警告メッセージが出力され、coverage=0.0000となった")
print("   - ただし、calculate_longterm_performanceで除外されるため、エラーにはならない")
print()

print("=" * 80)
print("修正後の動作")
print("=" * 80)
print()

print("✅ _get_next_trading_dayが価格データがNULLでない最初の営業日を返すように修正")
print("   - 2020-09-30のリバランス日 → 2020-10-02（金曜日）が返される")
print("   - 2020-10-02には正常な価格データがあるため、購入価格が正しく取得できる")
print("   - 月次リバランスでも長期保有型でも、同じように動作する")
print()

